#============================================================
#application-prod.yml (μ΄μ ν™κ²½ μ „μ©)
#λ©μ : μ΄μ DB μ ‘μ† μ •λ³΄
#μ£Όμ: λΉ„λ°€λ²νΈλ” ν™κ²½λ³€μ/μ‹ν¬λ¦Ώλ΅ μ£Όμ…. μ‹¤μ  μ£Όμ†λ΅ κµμ²΄.
#============================================================
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe # π›  μ΄μ DB μ£Όμ†/μ„λΉ„μ¤λ…μΌλ΅ κµμ²΄
    username: gym
    password: 1234                       # π” μ™Έλ¶€ μ£Όμ…(ν™κ²½λ³€μ/μ‹ν¬λ¦Ώ)